version: '3.9'
services:
  jenkins:
    build: ./image
    init: true
    restart: always
    ports:
      - 9081:8080
    networks:
      - poc-tlf-network
    volumes:
      - jenkins-data:/var/jenkins_home

networks:
  poc-tlf-network:
    driver: bridge

volumes:
  jenkins-data: