name: Build Heroku

on:
  release:
    types: [ created ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: '[heroku] download & install CLI'
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      # - name: '[heroku] set container'
      #   run: heroku stack:set container --app telefonica-jenkins

      # - name: '[heroku] Get API Key'
      #   id: heroku-api-key
      #   run: heroku auth:token >> $GITHUB_OUTPUT
        
      # - name: Show API Key
      #   run: echo "API Key is ( ${{ steps.heroku-api-key.outputs }} )"
        
#       - name: Heroku Login
#         run: heroku login
